namespace: dj
replicaCount: 1

image:
  repository: 038030846741.dkr.ecr.ap-northeast-2.amazonaws.com/nodeapp
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 0.0.4

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

livenessProbe:
  path: /healthz
  port: 3000

serviceAccount:
  create: true
  annotations: {
    eks.amazonaws.com/role-arn: arn:aws:iam::038030846741:role/lab-ct-global-nodeapp-role
  }
  name: "nodeapp"

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  targetPort: 3000
  port: 3000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
