apiVersion: v1
kind: Service
metadata:
  name: nodeapp
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    role: nodeapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nodeapp
  template:
    metadata:
      labels:
        role: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: 038030846741.dkr.ecr.ap-northeast-2.amazonaws.com/nodeapp:0.0.4
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
